import axios, { AxiosResponse } from 'axios';

const apiType = {
  get: 'get',
};

class Httppp {
  static getUser(): Promise<AxiosResponse<IUserDTO>> {
    return new Promise((resolve, reject) => {
      axios.get('https://jsonplaceholder.typicode.com/posts').then(resolve).catch(reject);
    });
  }
}

export { apiType, Httppp };

// Generated by https://quicktype.io

export type IUserDTO = {
  userId: number;
  id: number;
  title: string;
  body: string;
}[];
